nameOverride: ""
fullnameOverride: ""

image:
  repository: ctrlplane/job-policy-checker
  tag: latest
  pullPolicy: Always

extraEnv: {}
extraEnvFrom: {}

cron:
  labels: {}
  annotations: {}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  schedule: "*/1 * * * *" # every minute
  suspend: false

tolerations: []
pod: {}

serviceAccount:
  create: false
  name: ""

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 4000m
    memory: 4Gi
