{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      {{- include "ctrlplane.selectorLabels" $ | nindent 6 }}
      {{- include "web.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "web.serviceAccountName" . }}
      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      {{- include "ctrlplane.nodeSelector" . | nindent 6 }}
      {{- include "ctrlplane.priorityClassName" . | nindent 6 }}
      {{- include "ctrlplane.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: BASE_URL
              value: {{ .Values.global.fqdn }}
            - name: AUTH_URL
              value: {{ .Values.global.fqdn }}
            {{- include "ctrlplane.extraEnv" . | nindent 12 }}
            {{- include "ctrlplane.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          # livenessProbe:
          #   httpGet:
          #     path: /api/healthz
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /api/healthz
          #     port: http
          # startupProbe:
          #   httpGet:
          #     path: /api/healthz
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}