{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webservice.fullname" . }}
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      {{- include "ctrlplane.selectorLabels" $ | nindent 6 }}
      {{- include "webservice.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webservice.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "webservice.serviceAccountName" . }}
      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      {{- include "ctrlplane.nodeSelector" . | nindent 6 }}
      {{- include "ctrlplane.priorityClassName" . | nindent 6 }}
      {{- include "ctrlplane.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: webservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "ctrlplane.chart" . }}-connections
                  key: REDIS_URL
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "ctrlplane.chart" . }}-connections
                  key: POSTGRES_URL
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "webservice.fullname" . }}
                  key: AUTH_SECRET
            - name: GITHUB_URL
              value: {{ .Values.github.url }}
            - name: GITHUB_BOT_NAME
              value: {{ .Values.github.bot.name }}
            - name: GITHUB_BOT_APP_ID
              value: {{ .Values.github.bot.appId }}
            - name: GITHUB_BOT_CLIENT_ID
              value: {{ .Values.github.bot.clientId }}
            - name: GITHUB_BOT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ctrlplane.chart" . }}-connections
                  key: GITHUB_BOT_CLIENT_SECRET
            - name: GITHUB_BOT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ctrlplane.chart" . }}-connections
                  key: GITHUB_BOT_PRIVATE_KEY
            {{- include "ctrlplane.extraEnv" . | nindent 12 }}
            {{- include "ctrlplane.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
          startupProbe:
            httpGet:
              path: /api/healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}