nameOverride: ""
fullnameOverride: ""

replica: 1

image:
  repository: ctrlplane/workspace-engine-router
  tag: latest
  pullPolicy: Always

extraEnv: {}
extraEnvFrom: {}

deployment:
  labels: {}
  annotations: {}

hpa:
  labels: {}
  annotations: {}
  minReplicas: 1
  maxReplicas: 1

service:
  type: ClusterIP
  annotations: {}
  labels: {}

tolerations: []
pod: {}

serviceAccount:
  create: false
  name: ""
  annotations: {}
  labels: {}

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 4000m
    memory: 4Gi
