apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "event-queue.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "event-queue.labels" . | nindent 4 }}
    {{- if .Values.hpa.labels -}}
    {{-   toYaml .Values.hpa.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.hpa.annotations -}}
    {{-   toYaml .Values.hpa.annotations | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "event-queue.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70