{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "event-queue.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "event-queue.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.labels -}}
    {{-   toYaml .Values.serviceAccount.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.serviceAccount.annotations -}}
    {{-   toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
{{- end }}