nameOverride: ""
fullnameOverride: ""

activeDeadlineSeconds: 3600
backoffLimit: 6

image:
  repository: ctrlplane/migrations
  tag: latest
  pullPolicy: Always

extraEnv: {}
extraEnvFrom: {}

tolerations: []
pod: {}

job:
  labels: {}
  annotations: {}

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 4Gi
