{{- $secretName := (include "webservice.fullname" .)  }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
data:
{{- if $secret }}
  AUTH_SECRET: {{ $secret.data.AUTH_SECRET }}
{{- else }}
  AUTH_SECRET: {{ randAlphaNum 64 | b64enc }}
{{- end }}