apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel.fullname" . }}
  labels:
    {{- include "otel.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ctrlplane.selectorLabels" $ | nindent 6 }}
      {{- include "otel.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel.commonLabels" . | nindent 8 }}
        {{- include "otel.podLabels" . | nindent 8 }}
        {{- include "otel.labels" . | nindent 8 }}
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 4 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "otel.serviceAccountName" . }}
      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      {{- include "ctrlplane.nodeSelector" . | nindent 6 }}
      {{- include "ctrlplane.priorityClassName" . | nindent 6 }}
      {{- include "ctrlplane.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /otelcol-contrib
            - --config=/conf/config.yaml
          ports:
            - name: otlp
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: prometheus
              containerPort: 9109
              protocol: TCP
            - name: statsd
              containerPort: 8125
              protocol: TCP
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            {{- include "otel.extraEnv" (dict "global" $.Values.global "local" .Values) | nindent 12 }}
            {{- include "ctrlplane.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /conf
              name: config
      volumes:
        - name: config
          configMap:
            name: {{ include "otel.fullname" . }}
            items:
              - key: config
                path: config.yaml
      hostNetwork: false
