{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "event-worker.fullname" . }}
  labels:
    {{- include "event-worker.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      {{- include "ctrlplane.selectorLabels" $ | nindent 6 }}
      {{- include "event-worker.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "event-worker.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "event-worker.serviceAccountName" . }}
      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      {{- include "ctrlplane.nodeSelector" . | nindent 6 }}
      {{- include "ctrlplane.priorityClassName" . | nindent 6 }}
      {{- include "ctrlplane.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: event-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-connections
                  key: REDIS_URL
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-connections
                  key: POSTGRES_URL
            - name: VARIABLES_AES_256_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-encryption-key
                  key: AES_256_KEY
            {{- with (include "ctrlplane.githubBot" . | fromYaml) }}
            - name: GITHUB_BOT_APP_ID
              value: {{ .appId | quote }}
            - name: GITHUB_BOT_CLIENT_ID
              value: {{ .clientId | quote }}
            - name: GITHUB_BOT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .secretRef }}
                  key: GITHUB_BOT_CLIENT_SECRET
                  optional: true
            - name: GITHUB_BOT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .secretRef }}
                  key: GITHUB_BOT_PRIVATE_KEY
                  optional: true
            - name: GITHUB_BOT_NAME
              value: {{ .name }}
            {{- end }}
            {{- with (include "ctrlplane.azureApp" . | fromYaml) }}
            - name: AZURE_APP_CLIENT_ID
              value: {{ .clientId | quote }}
            - name: AZURE_APP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .secretRef }}
                  key: AZURE_APP_CLIENT_SECRET
                  optional: true
            {{- end }}
            {{- include "ctrlplane.extraEnv" . | nindent 12 }}
            {{- include "ctrlplane.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}