nameOverride: ""
fullnameOverride: ""

replica: 1

image:
  repository: ctrlplane/event-queue
  tag: latest
  pullPolicy: Always

pgbouncer:
  image:
    repository: ctrlplane/pgbouncer
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  internalPort: 6379
  config:
    listen_addr: 0.0.0.0
    listen_port: 6432
    unix_socket_dir: ""

extraEnv: {}
extraEnvFrom: {}

deployment:
  labels: {}
  annotations: {}

hpa:
  labels: {}
  annotations: {}
  minReplicas: 1
  maxReplicas: 5

tolerations: []
pod: {}

serviceAccount:
  create: false
  name: ""
  labels: {}
  annotations: {}

resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 4000m
    memory: 4Gi
