nameOverride: ""
fullnameOverride: ""

replica: 1

image:
  repository: ctrlplane/event-queue
  tag: latest
  pullPolicy: Always

extraEnv: {}
extraEnvFrom: {}

deployment:
  labels: {}
  annotations: {}

hpa:
  labels: {}
  annotations: {}
  minReplicas: 1
  maxReplicas: 5

tolerations: []
pod: {}

serviceAccount:
  create: false
  name: ""
  labels: {}
  annotations: {}

resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 4000m
    memory: 4Gi
