{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wer.fullname" . }}
  labels:
    {{- include "wer.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      {{- include "wer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wer.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "wer.serviceAccountName" . }}
      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      {{- include "ctrlplane.nodeSelector" . | nindent 6 }}
      {{- include "ctrlplane.priorityClassName" . | nindent 6 }}
      {{- include "ctrlplane.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: router
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: proxy
              containerPort: 9090
              protocol: TCP
            - name: managment
              containerPort: 9091
              protocol: TCP
          env:
            - name: KAFKA_BROKERS
              value: {{ .Values.global.kafkaBrokers | quote }}

            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-connections
                  key: POSTGRES_URL
            {{- include "ctrlplane.extraEnv" . | nindent 12 }}
            {{- include "ctrlplane.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}