apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-workspace-engine-router
  labels:
    {{- include "wer.labels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{-   toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.service.annotations -}}
    {{-   toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9090
      protocol: TCP
      name: proxy
    - port: 9091
      protocol: TCP
      name: managment
  selector:
    {{- include "wer.labels" . | nindent 4 }}