name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add Helm Repo URL to Release
        run: |
          HELM_REPO_URL="https://sizzldev.github.io/ctrlplane-charts/"
          RELEASE_ID=$(gh release list --limit 1 | awk '{print $1}')
          gh release edit "$RELEASE_ID" --notes "You can add this Helm repository with: helm repo add my-repo $HELM_REPO_URL"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
